Completed Exercise
t-doan/c1023-code-solutions pull request #23
Opened 2023-10-30 22:34 UTC by t-doan

![html-relative-links](https://github.com/t-doan/c1023-code-solutions/assets/26643555/83c9046f-40c1-45d4-b963-85d1d26eca0e)

2023-10-30 23:00 UTC, shawnkost requested changes
Few changes here Tai!

2023-10-30 23:00 UTC, shawnkost commented on html-relative-links/about-me/about-me.html
> +      <li><a href="../about-me/about-me.html">About Me</a></li>
Since we are in the `about-me` folder, it should just be `about-me.html`

2023-10-30 23:00 UTC, shawnkost commented on html-relative-links/contact-us/contact-us.html
> +      <li><a href="../contact-us/contact-us.html">Contact Us</a></li>
Since we are in the `contact-us` folder, it should just be `contact-us.html`

2023-10-30 23:00 UTC, shawnkost commented on html-relative-links/projects/projects.html
> +      <li><a href="../projects/projects.html">Projects</a></li>
Since we are in the `projects` folder, it should just be `projects.html`

2023-10-30 23:04 UTC, t-doan reviewed
Made the corrections

2023-11-01 16:42 UTC, shawnkost approved these changes
👍🏻

2023-11-01 22:44 UTC, merged