completed exercise
t-doan/c1023-code-solutions pull request #34
Opened 2023-11-02 08:34 UTC by t-doan

![css-flexbox-1](https://github.com/t-doan/c1023-code-solutions/assets/26643555/c1d373d5-a599-4ca1-999f-67b8972d16c2)
![css-flexbox-2](https://github.com/t-doan/c1023-code-solutions/assets/26643555/2ee6a83d-8936-4ae5-b3f7-49ea298d6020)
![css-flexbox-3](https://github.com/t-doan/c1023-code-solutions/assets/26643555/c38fe5fd-434a-4670-855a-6c4ab45db429)
![css-flexbox-4](https://github.com/t-doan/c1023-code-solutions/assets/26643555/3b04e105-0cbf-44dd-904e-9c81148377e0)

2023-11-03 16:58 UTC, shawnkost requested changes
Few changes here Tai!

2023-11-03 16:58 UTC, shawnkost commented on css-flexbox/align-items.html
> +      }
This should be `.card-wrapper` rather than just `div`. You don't want to apply `flex-basis` to every single `div`

2023-11-03 16:58 UTC, shawnkost commented on css-flexbox/display-flex.html
> +      }
This should be `.card-wrapper` rather than just `div`. You don't want to apply `flex-basis` to every single `div`

2023-11-03 16:58 UTC, shawnkost commented on css-flexbox/flex-wrap.html
> +      }
This should be `.card-wrapper` rather than just `div`. You don't want to apply `flex-basis` to every single `div`

2023-11-03 16:58 UTC, shawnkost commented on css-flexbox/justify-content.html
> +      }
This should be `.card-wrapper` rather than just `div`. You don't want to apply `flex-basis` to every single `div`

2023-11-03 17:16 UTC, t-doan commented on css-flexbox/align-items.html
> +      }
fixed the changes

2023-11-03 17:17 UTC, t-doan commented on css-flexbox/display-flex.html
> +      }
made the changes

2023-11-03 17:17 UTC, t-doan commented on css-flexbox/flex-wrap.html
> +      }
made the changes

2023-11-03 17:18 UTC, t-doan commented on css-flexbox/justify-content.html
> +      }
made the changes

2023-11-06 16:16 UTC, shawnkost approved these changes
👍🏻

2023-11-06 17:04 UTC, merged