Completed exercise
t-doan/c1023-code-solutions pull request #35
Opened 2023-11-02 11:53 UTC by t-doan

![css-layout-classes](https://github.com/t-doan/c1023-code-solutions/assets/26643555/0f72531e-f0d9-42c5-a069-786b066d09a0)

2023-11-02 17:27 UTC, shawnkost requested changes
Some changes here Tai! Mostly the ones related to the last two rows. Those should have 2 different column names, the other ones are just suggestions

2023-11-02 17:27 UTC, shawnkost commented on css-layout-classes/index.html
> +        </div>
Both of these columns shouldn't have the same class name. One of these columns is bigger than the other, so they should have 2 different column classes

2023-11-02 17:27 UTC, shawnkost commented on css-layout-classes/index.html
> +      </div>
Same note above ^

2023-11-02 17:27 UTC, shawnkost commented on css-layout-classes/index.html
> +        </div>
Better name would probably be `column-third`. You want to name your column classes based off of how much space they will take up

2023-11-02 17:27 UTC, shawnkost commented on css-layout-classes/index.html
> +        </div>
`.column-fourth` would probably be better because these are 4 columns and not 1 full column

2023-11-02 21:08 UTC, t-doan reviewed
made the changes

2023-11-03 16:10 UTC, shawnkost approved these changes
👍🏻

2023-11-03 17:11 UTC, merged