Completed es6-classes
t-doan/c1023-code-solutions pull request #62
Opened 2023-11-21 22:58 UTC by t-doan

![es6-classes-1](https://github.com/t-doan/c1023-code-solutions/assets/26643555/80a8e8e7-6aa8-43e9-8e49-2fa43aea8e68)
![es6-classes-2](https://github.com/t-doan/c1023-code-solutions/assets/26643555/b1d40661-1592-4ede-b2a7-0dc37aef66a0)
![es6-classes-3](https://github.com/t-doan/c1023-code-solutions/assets/26643555/f1c016a1-4fb0-446a-8e90-2fd5e304cb77)

2023-11-21 23:00 UTC, shawnkost requested changes
Couple changes here Tai!

2023-11-21 23:00 UTC, shawnkost commented on es6-classes/circle.js
> +    super(radius);
You should be passing 2 arguments into this. One for your `perimeter`, and one for your `area`

2023-11-21 23:00 UTC, shawnkost commented on es6-classes/square.js
> +    super(width);
You should be passing 2 arguments into this. One for your `perimeter`, and one for your `area`

2023-11-21 23:11 UTC, shawnkost requested changes
Some more changes here Tai!

2023-11-21 23:11 UTC, shawnkost commented on es6-classes/circle.js
> +  constructor(area, perimeter, radius) {
This should only take 1 argument for your `radius`. Utilizing your `radius`, you need to calculate what `area` & `perimeter` should be, and that's what you pass into `super`

2023-11-21 23:11 UTC, shawnkost commented on es6-classes/circle.js
> +    return `${myShape.describe()} radius: ${this.radius}`;
This should be `super.describe()` rather than `myShape`

2023-11-21 23:11 UTC, shawnkost commented on es6-classes/square.js
> +  constructor(area, perimeter, width) {
This should only take 1 argument for your `width`. Utilizing your `width`, you need to calculate what `area` & `perimeter` should be, and that's what you pass into `super`

2023-11-21 23:11 UTC, shawnkost commented on es6-classes/square.js
> +    return `${myShape.describe()} width: ${this.width}`;
This should be `super.describe()` rather than `myShape`

2023-11-22 00:04 UTC, t-doan commented on es6-classes/circle.js
>      this.radius = radius;
Fixed the changes

2023-11-22 00:04 UTC, t-doan commented on es6-classes/circle.js
> +    return `${super.describe()} radius: ${this.radius}`;
Fixed the changes

2023-11-22 00:04 UTC, t-doan commented on es6-classes/square.js
> +    super(width * width, width * 4);
Fixed the changes

2023-11-22 00:04 UTC, t-doan commented on es6-classes/square.js
> +    return `${super.describe()} width: ${this.width}`;
Fixed the changes

2023-11-22 17:43 UTC, shawnkost approved these changes
👍🏻

2023-11-22 18:09 UTC, merged